---
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart sglang
  ansible.builtin.service:
    name: "{{ ct_runtime_sglang_service_name }}"
    state: restarted
