---
- name: Reload systemd
  ansible.builtin.systemd_service:
    daemon_reload: true

- name: Restart ollama
  ansible.builtin.service:
    name: "{{ ct_runtime_ollama_service_name }}"
    state: restarted
