---
- name: Manage CT lifecycle
  community.proxmox.proxmox:
    api_host: "{{ ct_instance_api_host }}"
    api_user: "{{ ct_instance_api_user }}"
    api_token_id: "{{ ct_instance_api_token_id }}"
    api_token_secret: "{{ ct_instance_api_token_secret }}"
    node: "{{ ct_instance_node }}"
    vmid: "{{ ct_instance_vmid }}"
    hostname: "{{ ct_instance_hostname }}"
    ostemplate: "{{ ct_instance_ostemplate }}"
    storage: "{{ ct_instance_storage }}"
    cores: "{{ ct_instance_cores }}"
    memory: "{{ ct_instance_memory }}"
    swap: "{{ ct_instance_swap }}"
    rootfs: "{{ ct_instance_storage }}:{{ ct_instance_rootfs_size }}"
    netif: "{{ ct_instance_netif }}"
    features: "{{ ct_instance_features }}"
    mounts: "{{ ct_instance_mounts }}"
    unprivileged: "{{ ct_instance_unprivileged }}"
    onboot: "{{ ct_instance_onboot }}"
    state: "{{ ct_instance_state }}"
  delegate_to: localhost
