---
galaxy_info:
  author: ktooi
  description: Role in ktooi.pve_inference collection.
  license: MIT
  min_ansible_version: "2.16"
  platforms:
    - name: Debian
      versions:
        - all
dependencies: []
